# Generated by Django 3.2.3 on 2022-09-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredientsrecipes', through='recipes.IngredientRecipe', to='recipes.Ingredient'),
        ),
    ]
